name: kasirq
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.5
  csv: ^5.0.1
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.1
  file_picker: ^5.2.6
  path_provider: ^2.0.14
  open_file: ^2.1.1
  get: ^4.6.5
  flutter_svg: ^1.1.6
  intl: ^0.18.1
  lottie: ^2.3.2
  external_path: ^1.0.3
  flutter_native_splash: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  - lib/assets/images/art_1.png
  - lib/assets/images/kasir.png
  - lib/assets/images/kasirq.png
  - lib/assets/images/substract.png
  - lib/assets/images/tea_dummy.png

    #Icons
  - lib/assets/icons/ic_box.svg
  - lib/assets/icons/ic_history.svg
  - lib/assets/icons/ic_transaction.svg

    #Animation
  - lib/assets/anim/success.json
  - lib/assets/anim/error.json
  - lib/assets/anim/payment-success.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/roboto/Roboto-Regular.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
